# Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  emails:
    - k.t.the-answer@hotmail.co.jp
  on_failure: always
after_success:
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("OnlinePCA")); include(joinpath("docs", "make.jl"))'
